### ISSUE TITLE
晴朗

### ISSUE THREAD

**Issue by littleflute** [littleflute/Songs#165]
https://www.youtube.com/watch?v=TCVf5LmMQGM&list=RDTCVf5LmMQGM&start_radio=1

**Comment by littleflute** [comment]
http://www.17jita.com/tab/img/7508.html

**Comment by littleflute** [comment]
https://littleflute.github.io/s165/

**Comment by shanuan** [comment]
dt:
https://mp.weixin.qq.com/s?__biz=MzA5MzMwNTc0Ng==&mid=2247492828&idx=2&sn=f0176482988097f906e1cdba1f97419c&chksm=905d4a21a72ac33711cb92874e1582ba288d15066cab1a7fb4150c8d36dc45d9a4f39e200b36&scene=178#rd

**Comment by shanuan** [comment]
https://github.com/littleflute/Songs/releases/tag/s165
